export const COOKBOOK = {
  app: 'cookbook-app',
  title: 'app-title',
  newRecipeBtn: 'new-recipe-btn',
  searchInput: 'search-input',
  ratingFilter: 'rating-filter',
  minCaloriesInput: 'min-calories-input',
  maxCaloriesInput: 'max-calories-input',
  findRecipesBtn: 'find-recipes-btn',
  recipeForm: 'recipe-form',
  closeFormBtn: 'close-form-btn',
  recipeNameInput: 'recipe-name-input',
  caloriesInput: 'calories-input',
  proteinInput: 'protein-input',
  carbsInput: 'carbs-input',
  fatInput: 'fat-input',
  newIngredientInput: 'new-ingredient-input',
  addIngredientBtn: 'add-ingredient-btn',
  submitRecipeBtn: 'submit-recipe-btn',
  cancelBtn: 'cancel-btn',
  matchedRecipes: 'matched-recipes',
  recipesGrid: 'recipes-grid',
  emptyState: 'empty-state',
  recipeCard: (id) => `recipe-card-${id}`,
  recipeName: 'recipe-name',
  editRecipeBtn: 'edit-recipe-btn',
  deleteRecipeBtn: 'delete-recipe-btn',
  recipeNutrients: 'recipe-nutrients',
  recipeIngredients: 'recipe-ingredients',
  ratingStars: 'rating-stars',
  star: (num) => `star-${num}`,
  cookedBtn: 'cooked-btn'
};